In [1]:
import numpy as np
import pandas as pd

In [2]:
#Paremeters
num_doctors = 3 # number of doctors
num_patients =5 # number of patient
num_states = num_doctors * num_patients  # Total States
num_action = num_doctors # Assign a patient to one of a doctor

In [3]:
# Initialize a Q-table with zero entrys
Q_table = np.zeros((num_patients,num_action ))

In [4]:
Q_table

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
#Hyperparameters
alpha = 0.1 #Learning Rate
gamma = 0.9 #Discount factor
epsilon = 0.2 #Exploration Rate
num_epsiodes = 1000 #Training Epsiode

In [10]:
# Time matrix (randomized time taken by doctors for each patient)
time_matrix = np.random.randint(5, 20, (num_patients, num_doctors))  # (Patients x Doctors)

In [12]:
import random
#Q_learning Loop
for epsiodes in range(num_epsiodes):
    for patients in range(num_patients):
        if random.uniform(0,1) < epsilon:
            action = np.random.choice(num_action) # Explore: Random doctor assignment
        else:
            action = np.argmax(Q_table[patients])  # Exploit: Best known assignment
        reward = -time_matrix[patients , action]  # Negative time to minimize it

        # Update Q-value using Bellman equation
        Q_table[patients, action] = (1 - alpha) * Q_table[patients, action] + \
                                   alpha * (reward + gamma * np.max(Q_table[patients]))
# Optimal doctor assignment based on learned Q-values
optimal_assignment = np.argmax(Q_table, axis=1)   

In [13]:
def display_results():
    print("Time Matrix (Patients x Doctors):")
    print(time_matrix)
    print("\nLearned Q-Table:")
    print(Q_table)
    print("\nOptimal Assignment of Patients to Doctors:")
    for p in range(num_patients):
        print(f"Patient {p} -> Doctor {optimal_assignment[p]}")

# Display results
display_results()

Time Matrix (Patients x Doctors):
[[14  6  7]
 [18 13 12]
 [ 6 18 11]
 [17 16 14]
 [18  6 19]]

Learned Q-Table:
[[ -67.24297598  -59.94659678  -60.75651799]
 [-124.874191   -120.05283148 -119.71793812]
 [ -59.97817802  -71.70875894  -64.88196095]
 [-141.22601723 -140.59583282 -139.6636387 ]
 [ -71.71218405  -59.98509758  -72.81477265]]

Optimal Assignment of Patients to Doctors:
Patient 0 -> Doctor 1
Patient 1 -> Doctor 2
Patient 2 -> Doctor 0
Patient 3 -> Doctor 2
Patient 4 -> Doctor 1
